// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_S080XFzqsFYKeIhw3RJXnAEhtvFomV0',
    appId: '1:204864276768:web:d1c4f360041056f1206f45',
    messagingSenderId: '204864276768',
    projectId: 'memehub-15e30',
    authDomain: 'memehub-15e30.firebaseapp.com',
    storageBucket: 'memehub-15e30.appspot.com',
    measurementId: 'G-C6HJRD1E8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNGMhPaCdhVGmW3IWxHHs0p0pRbAy8qbg',
    appId: '1:204864276768:android:b86db6f5602de1fc206f45',
    messagingSenderId: '204864276768',
    projectId: 'memehub-15e30',
    storageBucket: 'memehub-15e30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7Y9m2kZzq9uxU4SN19ZYEr2mZBvJN3Y',
    appId: '1:204864276768:ios:71379f6f741d6c52206f45',
    messagingSenderId: '204864276768',
    projectId: 'memehub-15e30',
    storageBucket: 'memehub-15e30.appspot.com',
    iosBundleId: 'com.memehub.memehubMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk7Y9m2kZzq9uxU4SN19ZYEr2mZBvJN3Y',
    appId: '1:204864276768:ios:96a82c8fbafa2e16206f45',
    messagingSenderId: '204864276768',
    projectId: 'memehub-15e30',
    storageBucket: 'memehub-15e30.appspot.com',
    iosBundleId: 'com.memehub.memehubMobileApp.RunnerTests',
  );
}
